APP_SETTINGS = {
    'known_apps': {
        "WINWORD.EXE": "Word",
        "POWERPNT.EXE": "PowerPoint",
        "EXCEL.EXE": "Excel",
        "chrome.exe": "Browser",
        "firefox.exe": "Browser",
        "msedge.exe": "Browser",
        # Add other executable names for browsers or additional applications
    },
    'settings_file': 'settings.json',
    'activities_file': 'activities.json',
    'feedback_file': 'feedback.txt',
    'shortcuts': {
        "ctrl+c": "Copy",
        "ctrl+v": "Paste",
        "ctrl+x": "Cut",
        "alt+tab": "Switch windows",
        "win+x": "Quick Link Menu",
        "ctrl+y": "Redo",
        "ctrl+z": "Undo",
        "ctrl+shift+n": "Create New Folder / Incognito",
        "ctrl+shift+esc": "Task Manager",
        "shift+win+s": "Screen Shot",
        "ctrl+i": "Apply Italic",
        "ctrl+u": "Apply Underline",
        "ctrl+b": "Apply Bold",
        "ctrl+e": "Center Text",
        "ctrl+n": "Create new document / presentation / window",
        "ctrl+s": "Save",
        "ctrl+]": "Increase font size",
        "ctrl+[": "Decrease font size",
        "ctrl+j": "Justify text",
        "ctrl+f1": "Toggle Ribbon",
        "ctrl+m": "Add a new slide in PPT",
        "f5": "Start presentation in PPT",
        "ctrl+d": "Duplicate object in PPT / Bookmark current page",
        "ctrl+g": "Group object in PPT",
        "ctrl+t": "Open new tab",
        "ctrl+w": "Close current tab",
        "ctrl+tab": "Switch to the next tab",
        "ctrl+shift+tab": "Switch to the previous tab",
        "ctrl+shift+t": "Reopen the last closed tab",
        "ctrl+l": "Focus the address bar",
        "ctrl+h": "Open history",
        "ctrl+a": "Select all",
        # Add more shortcuts as needed
    }
}